---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    - cron: '30 1 * * 3'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      container_supported: ${{ steps.get_min_ansible_container_version.outputs.result }}
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Pull Lint image
        run: docker pull -q ghcr.io/rheinwerk/molecule:lint

      - name: Ansible Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git ghcr.io/rheinwerk/molecule:lint ansible-lint --force-color -p --offline /git

      - name: Yaml Linting
        run: docker run --rm -v ${GITHUB_WORKSPACE}:/git -w /git ghcr.io/rheinwerk/molecule:lint yamllint -f colored /git

      - name: Get min_ansible_container_version from meta/main.yml
        id: get_min_ansible_container_version
        uses: mikefarah/yq@master
        with:
          cmd: yq ".galaxy_info.min_ansible_container_version" ${GITHUB_WORKSPACE}/meta/main.yml

  molecule:
    name: Molecule for Ansible ${{ matrix.ansible_scenario }} / ${{ matrix.distro }} / Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    needs: lint
    if: needs.lint.outputs.container_supported != 'X'
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: debian-12
            ansible_scenario: ansible_current
            experimental: false
          - distro: debian-12
            ansible_scenario: ansible_next
            experimental: true
          - distro: debian-12
            ansible_scenario: ansible_latest
            experimental: true

    steps:
      - uses: Rheinwerk/molecule@main
        with:
          distro: ${{ matrix.distro }}
          ansible_scenario: ${{ matrix.ansible_scenario }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: molecule
    # https://github.com/actions/runner/issues/491#issuecomment-850884422
    if: |
      always() &&
      startsWith(github.event.ref, 'refs/tags/v') &&
      (needs.molecule.result == 'success' || needs.molecule.result == 'skipped')
    steps:
      # Ansible ist bereits im Ubuntu Image enthalten, wir brauchen keine spezielle Version f√ºr den Galaxy Import: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
      # AnsibleLint config wird anscheinend ignoriert: https://github.com/ansible/galaxy/issues/2868
      - name: Trigger import of Role at Ansible Galaxy
        run: |
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
